sudo: false

addons:
    apt_packages:
        - enchant

branches:
  except:
    - /^patch-.*$/

install:
    - pip install --user -r requirements.txt

script:
    - make SPHINXOPTS='-nW' html
    - make spelling
